[build]
  command = "npm run build"
  publish = "artifacts/commerce-shala/dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  BASE_PATH = "/"
  PORT = "3000"
